In [1]:
import torch
import cv2

In [3]:
torch.arange(1,11)



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\traitlets\config\application.py", line 1075, in launch_i

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
torch.__version__

'2.3.1+cpu'

In [5]:
scaler=torch.tensor(7)

In [6]:
scaler

tensor(7)

In [7]:
scaler.ndim

0

In [8]:
vector=torch.tensor([1,2])

In [9]:
vector

tensor([1, 2])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
scaler.shape

torch.Size([])

In [13]:
Matrix=torch.tensor([[1,2],[2,3],[3,4],[4,5]])

In [14]:
Matrix.ndim

2

In [15]:
Matrix.shape

torch.Size([4, 2])

In [16]:
Tensor=torch.rand(size=(3,4),device='cpu',dtype=float)

In [17]:
Tensor.device

device(type='cpu')

In [18]:
Tensor.ndim

2

In [19]:
Tensor.shape

torch.Size([3, 4])

In [20]:
Tensor

tensor([[0.9159, 0.0325, 0.0655, 0.8439],
        [0.0650, 0.9427, 0.0977, 0.5541],
        [0.0306, 0.3464, 0.7818, 0.0785]], dtype=torch.float64)

In [21]:
x=torch.zeros(size=(2,3),dtype=float)

In [22]:
y=torch.ones(size=(3,4),dtype=int)

In [23]:
x.shape,x.size(),x.ndim

(torch.Size([2, 3]), torch.Size([2, 3]), 2)

In [24]:
example=torch.arange(0,20,3)

In [25]:
example

tensor([ 0,  3,  6,  9, 12, 15, 18])

In [26]:
example2=torch.rand(3,4)

In [27]:
example2

tensor([[0.3648, 0.0711, 0.8013, 0.3928],
        [0.4124, 0.7149, 0.3863, 0.0856],
        [0.9491, 0.0795, 0.2099, 0.5033]])

In [28]:
example2+13

tensor([[13.3648, 13.0711, 13.8013, 13.3928],
        [13.4124, 13.7149, 13.3863, 13.0856],
        [13.9491, 13.0795, 13.2099, 13.5033]])

In [29]:
example2*2

tensor([[0.7296, 0.1422, 1.6026, 0.7856],
        [0.8247, 1.4299, 0.7726, 0.1711],
        [1.8983, 0.1589, 0.4198, 1.0066]])

In [30]:
example2/2

tensor([[0.1824, 0.0356, 0.4007, 0.1964],
        [0.2062, 0.3575, 0.1932, 0.0428],
        [0.4746, 0.0397, 0.1049, 0.2517]])

In [31]:
example2-12

tensor([[-11.6352, -11.9289, -11.1987, -11.6072],
        [-11.5876, -11.2851, -11.6137, -11.9144],
        [-11.0509, -11.9205, -11.7901, -11.4967]])

In [32]:
# torch.matmul(example2,example)

In [33]:
example.shape,example2.shape

(torch.Size([7]), torch.Size([3, 4]))

In [34]:
# torch.matmul(example2,example2)

In [35]:
example2.T

tensor([[0.3648, 0.4124, 0.9491],
        [0.0711, 0.7149, 0.0795],
        [0.8013, 0.3863, 0.2099],
        [0.3928, 0.0856, 0.5033]])

In [36]:
z=torch.matmul(example2,example2.T)

In [37]:
example2.min

<function Tensor.min>

In [38]:
example2.min()

tensor(0.0711)

In [39]:
example2.argmin()

tensor(1)

In [40]:
z.argmin()

tensor(1)

In [41]:
z[2]

tensor([0.7178, 0.5723, 1.2045])

In [42]:
z

tensor([[0.9345, 0.5444, 0.7178],
        [0.5444, 0.8377, 0.5723],
        [0.7178, 0.5723, 1.2045]])

In [43]:
z[2].argmin()

tensor(1)

In [44]:
z[1].sum()

tensor(1.9545)

In [45]:
z[0].sum()

tensor(2.1968)

In [46]:
z[2].sum()

tensor(2.4947)

In [47]:
z.mean()

tensor(0.7384)

In [48]:
z.median()

tensor(0.7178)

In [49]:
z.mode()

torch.return_types.mode(
values=tensor([0.5444, 0.5444, 0.5723]),
indices=tensor([1, 0, 1]))

In [50]:
z.reshape(shape=(1,9))

tensor([[0.9345, 0.5444, 0.7178, 0.5444, 0.8377, 0.5723, 0.7178, 0.5723, 1.2045]])

In [51]:
z.reshape(shape=(9,1))

tensor([[0.9345],
        [0.5444],
        [0.7178],
        [0.5444],
        [0.8377],
        [0.5723],
        [0.7178],
        [0.5723],
        [1.2045]])

In [52]:
z1=torch.stack([z,z])

In [53]:
z1

tensor([[[0.9345, 0.5444, 0.7178],
         [0.5444, 0.8377, 0.5723],
         [0.7178, 0.5723, 1.2045]],

        [[0.9345, 0.5444, 0.7178],
         [0.5444, 0.8377, 0.5723],
         [0.7178, 0.5723, 1.2045]]])

In [54]:
torch.stack([x,y,z])

RuntimeError: stack expects each tensor to be equal size, but got [2, 3] at entry 0 and [3, 4] at entry 1

In [ ]:
torch.stack([z,z],dim=0)

In [ ]:
torch.stack([z,z],dim=1)

In [ ]:
torch.stack([z,z],dim=2)

In [ ]:
torch.stack([z,z],dim=-2)

In [ ]:
torch.stack([z,z],dim=-3)

In [ ]:
new=torch.rand(size=(7,6,5))

In [ ]:
new

tensor([[[0.6252, 0.9925, 0.4010, 0.6503, 0.0693],
         [0.1633, 0.5462, 0.5570, 0.5562, 0.5665],
         [0.6069, 0.1850, 0.2888, 0.2340, 0.5893],
         [0.7480, 0.7210, 0.8334, 0.1000, 0.5916],
         [0.9957, 0.2848, 0.9254, 0.2481, 0.6533],
         [0.1112, 0.5768, 0.5081, 0.0627, 0.3947]],

        [[0.0397, 0.6845, 0.9239, 0.0328, 0.0266],
         [0.3472, 0.2770, 0.1710, 0.4058, 0.7052],
         [0.0919, 0.4356, 0.3854, 0.2009, 0.6960],
         [0.0327, 0.0417, 0.1392, 0.5350, 0.6950],
         [0.7105, 0.9007, 0.7582, 0.1855, 0.3101],
         [0.6275, 0.7347, 0.3338, 0.5236, 0.1218]],

        [[0.4487, 0.8917, 0.0977, 0.8882, 0.3890],
         [0.5861, 0.0702, 0.9518, 0.5062, 0.6007],
         [0.3810, 0.2727, 0.4704, 0.3143, 0.7420],
         [0.6514, 0.6672, 0.4266, 0.2357, 0.6573],
         [0.6367, 0.9376, 0.2290, 0.5158, 0.6033],
         [0.4743, 0.0866, 0.3784, 0.0452, 0.7434]],

        [[0.7882, 0.7252, 0.4259, 0.8445, 0.8628],
         [0.8551, 0.8875,

In [ ]:
new1=new.squeeze()
new1.shape

torch.Size([7, 6, 5])

In [ ]:
new2=new1.permute(2,0,1)
new2.shape

torch.Size([5, 7, 6])

In [ ]:
new3=torch.arange(1,11).reshape(1,5,2)

In [ ]:
new3

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]])

In [ ]:
new3[0,:,1]

tensor([ 2,  4,  6,  8, 10])

In [ ]:
!nvidia-smi

Mon Jun 24 12:01:09 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.34                 Driver Version: 537.34       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650 Ti   WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   35C    P8               5W /  41W |      0MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [55]:
import torch
torch.cuda.is_available()

False

In [80]:
weight = 0.7
bias = 0.3



start = 0
end=1
step= 0.02

x=torch.arange(start,end,step).unsqueeze(dim=1)

y=weight*x+bias
# y=mx+c
# linear formula


x[:10],y[:10]
  

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [84]:
train_split = int(0.8 * len(x)) # 80% of data used for training set, 20% for testing 
X_train, y_train = x[:train_split], y[:train_split]
X_test, y_test = x[train_split:], y[train_split:]

len(X_train), len(y_train), len(X_test), len(y_test)

(40, 40, 10, 10)

In [85]:
from torch import nn



class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.weight=nn.Parameter(torch.randn(1,
                                             requires_grad=True,
                                             dtype=float))
        self.bias=nn.Parameter(torch.randn(1,
                                             requires_grad=True,
                                             dtype=float))
        # here 1 describes the dim of the tensor
    # this forward is the member function
    def Forward (self,x:torch.Tensor) -> torch.Tensor:
        # here x:torch.Tensor is the x=data :torch.Tensor=expected data type
        # -> this denotes the return type

        return self.weight * x +self.bias
    # linear formula



In [86]:
torch.manual_seed(42)

model_0=LinearRegressionModel()

list(model_0.parameters())

[Parameter containing:
 tensor([0.3367], dtype=torch.float64, requires_grad=True),
 Parameter containing:
 tensor([0.1288], dtype=torch.float64, requires_grad=True)]

In [87]:
model_0.state_dict()
weight,bias

(0.7, 0.3)

In [89]:
with torch.inference_mode():
    y_preds=model_0(X_test)

y_preds

NotImplementedError: Module [LinearRegressionModel] is missing the required "forward" function